### **Física do Clima**

Análise de Dados MOVAR - ERA5

In [33]:
import pandas as pd
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
import datetime
import xarray as xr
import math

In [4]:
# Abrindo os dados
dados = loadmat('dataset/DadosMovar.mat')

In [6]:
dados.keys()

dict_keys(['__header__', '__version__', '__globals__', 'SSH_movar', 'VEL_movar', 'None', 'latitude', 'longitude', 'profundidade', 'salinidade', 'temperatura', '__function_workspace__'])

In [6]:
# Transformando em Xarray...

In [7]:
print(dados['latitude'].shape)
print(dados['temperatura'].shape)
print(dados['SSH_movar'].shape)
print(dados['profundidade'].shape)

(48, 1)
(81, 48, 77)
(48, 77)
(1, 81)

In [85]:
lat = dados['latitude'].tolist()
lon = dados['longitude'].tolist()

[-23.0]

In [89]:
#def mat_to_xarray(data):
    
#     lat = [[row.flat[0] for row in line] for line in data['latitude']]
#     lon = [[row.flat[0] for row in line] for line in data['longitude']]
#     temp = [[row.flat[0] for row in line] for line in data['temperatura']]
#     sal = [[row.flat[0] for row in line] for line in data['salinidade']]
#     ssh_movar = [[row.flat[0] for row in line] for line in data['SSH_movar']]
    
#     cruize = np.arange(1,len(ssh_movar[0]),1)
    
#     temp_xr = xr.DataArray(
#         data = temp,
#         dims = ['x', 'y', 'cruize'],
#         coords = dict(
#             lon = (['x','y'], lon),
#             lat = (['x','y'], lat),
#             cruize = cruize
#     ))

    
    
        
    
#    return temp_xr

In [55]:

# data_vars = {'temperatura':(['profundidade', 'estacao', 'cruzeiro'], dados['temperatura'],
#                             {'units': 'degC',
#                              'long-name':'Temperatura'})}

# coords = dict(
#     profundidade = (['profundidade'], new_prof),
#     estacao = (['estacao'], np.arange(1,49,1)),
#     cruzeiro = (['cruzeiro'], np.arange(1,78,1)))

In [8]:
# ds = xr.Dataset(data_vars = data_vars,
#                 coords = coords)

temp = [[row.flat[0] for row in line] for line in dados['temperatura'][0]]

In [9]:
tsm = dados['temperatura'][0]

In [10]:
station = 1
station_name = list()
while station <= 48:
    name = "E_" + str(station)
    station_name.append(name)
    station += 1
    
cruize = 1
cruize_name = list()
while cruize <= 77:
    name = "CRUIZE_" + str(cruize)
    cruize_name.append(name)
    cruize += 1

In [11]:
# Criando DataFrame:

tsm_movar_hist = pd.DataFrame(columns = station_name)

In [12]:
for station, hist_data in zip(station_name, tsm):
    tsm_movar_hist[station] = hist_data

In [13]:
tsm_movar_hist["CRUIZE"] = cruize_name

In [14]:
tsm_movar_hist.set_index('CRUIZE', inplace=True)

In [15]:
tsm_movar_hist

,E_1,E_2,E_3,E_4,E_5,E_6,E_7,E_8,E_9,E_10,...,E_39,E_40,E_41,E_42,E_43,E_44,E_45,E_46,E_47,E_48
CRUIZE,,,,,,,,,,,,,,,,,,,,,
CRUIZE_1,23.499226,23.756531,23.770879,23.747252,23.717516,23.730860,23.752800,23.638517,23.471465,23.248038,...,23.547429,23.810055,23.760576,23.613674,23.491007,23.449859,23.439000,23.467945,23.532576,23.581247
CRUIZE_2,26.896834,26.818156,26.733801,26.675473,26.649647,26.688782,26.848778,27.144192,27.240274,27.135807,...,27.395975,27.399053,27.437994,27.595545,27.766973,27.812037,27.715937,27.486350,27.205830,27.104429
CRUIZE_3,24.060687,24.041373,24.038529,24.067926,24.093573,24.073169,23.947617,23.855217,23.850083,23.843946,...,23.295734,23.336801,23.329103,23.278467,23.373334,23.627349,23.821648,23.798427,23.654654,23.583798
CRUIZE_4,27.920818,27.387925,27.049383,26.888952,26.854583,26.896871,26.833469,26.915357,27.306002,27.708478,...,27.918611,27.818803,27.714721,27.703243,27.753873,27.771777,27.751768,27.713510,27.673000,27.604952
CRUIZE_5,23.489762,23.477425,23.476364,23.502066,23.565956,23.735893,23.986648,24.177905,24.246228,24.184116,...,24.407720,24.395638,24.220213,24.083416,24.089854,24.157630,24.124323,24.044972,23.878790,23.816418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CRUIZE_73,27.970725,28.101742,28.166455,28.070844,27.841630,27.426962,27.149527,27.187947,27.412331,27.741340,...,28.396850,28.492883,28.648761,28.826165,28.867447,28.778074,28.646931,28.657936,28.746724,28.761636
CRUIZE_74,25.952224,25.863486,25.840418,25.828224,25.829098,25.828189,25.619914,25.254589,25.084594,25.310170,...,26.243863,26.286676,26.067433,25.730990,25.518824,25.519546,25.647269,25.827318,25.951070,25.912387
CRUIZE_75,24.035221,24.088006,24.188302,24.247570,24.258114,24.206855,24.178079,24.209145,24.227793,24.260977,...,23.839929,23.888201,24.020703,24.078783,23.975659,23.845363,23.753467,23.749874,23.777295,23.802165
CRUIZE_76,23.986064,23.882506,23.818169,23.704893,23.546676,23.375895,23.714042,24.312327,24.369032,23.989924,...,24.181560,24.119930,23.986254,23.925357,24.025383,24.142002,24.059272,23.953354,23.944849,23.970898
CRUIZE_77,25.176564,25.276261,25.239682,25.040907,24.781608,24.570216,24.853454,25.279052,25.391712,25.446215,...,25.708491,25.935663,26.248332,26.263723,25.917856,25.567011,25.602760,25.813945,26.023470,25.926042

# Datas MOVAR

In [16]:
dates = loadmat("dataset/datas.mat")

In [23]:
date_movar = dates['date']

In [53]:
teste

732369.3791666667

In [71]:
def datenum_to_datetime(datenum):
    
    date_time = dt.fromordinal(int(datenum)) + timedelta(days=teste%1) - timedelta(days = 366)
    
    return date_time

In [72]:
new_dates = [] 
for pair in date_movar:

    dates = [datenum_to_datetime(x) for x in pair]
    new_dates.append(dates)

In [76]:
new_dates

[[datetime.datetime(2004, 8, 29, 9, 5, 59, 999999),
  datetime.datetime(2004, 9, 2, 9, 5, 59, 999999)],
 [datetime.datetime(2005, 2, 17, 9, 5, 59, 999999),
  datetime.datetime(2005, 2, 26, 9, 5, 59, 999999)],
 [datetime.datetime(2005, 8, 12, 9, 5, 59, 999999),
  datetime.datetime(2005, 8, 22, 9, 5, 59, 999999)],
 [datetime.datetime(2006, 2, 14, 9, 5, 59, 999999),
  datetime.datetime(2006, 2, 21, 9, 5, 59, 999999)],
 [datetime.datetime(2006, 6, 30, 9, 5, 59, 999999),
  datetime.datetime(2006, 7, 2, 9, 5, 59, 999999)],
 [datetime.datetime(2006, 8, 16, 9, 5, 59, 999999),
  datetime.datetime(2006, 8, 18, 9, 5, 59, 999999)],
 [datetime.datetime(2006, 12, 11, 9, 5, 59, 999999),
  datetime.datetime(2006, 12, 14, 9, 5, 59, 999999)],
 [datetime.datetime(2007, 2, 25, 9, 5, 59, 999999),
  datetime.datetime(2007, 2, 28, 9, 5, 59, 999999)],
 [datetime.datetime(2007, 3, 5, 9, 5, 59, 999999),
  datetime.datetime(2007, 3, 7, 9, 5, 59, 999999)],
 [datetime.datetime(2007, 4, 21, 9, 5, 59, 999999),
  datetime.datetime(2007, 4, 24, 9, 5, 59, 999999)],
 [datetime.datetime(2007, 6, 27, 9, 5, 59, 999999),
  datetime.datetime(2007, 6, 29, 9, 5, 59, 999999)],
 [datetime.datetime(2007, 8, 24, 9, 5, 59, 999999),
  datetime.datetime(2007, 8, 27, 9, 5, 59, 999999)],
 [datetime.datetime(2008, 2, 15, 9, 5, 59, 999999),
  datetime.datetime(2008, 2, 16, 9, 5, 59, 999999)],
 [datetime.datetime(2008, 4, 17, 9, 5, 59, 999999),
  datetime.datetime(2008, 4, 19, 9, 5, 59, 999999)],
 [datetime.datetime(2008, 6, 11, 9, 5, 59, 999999),
  datetime.datetime(2008, 6, 13, 9, 5, 59, 999999)],
 [datetime.datetime(2008, 8, 19, 9, 5, 59, 999999),
  datetime.datetime(2008, 8, 21, 9, 5, 59, 999999)],
 [datetime.datetime(2008, 12, 6, 9, 5, 59, 999999),
  datetime.datetime(2008, 12, 8, 9, 5, 59, 999999)],
 [datetime.datetime(2009, 2, 3, 9, 5, 59, 999999),
  datetime.datetime(2009, 2, 5, 9, 5, 59, 999999)],
 [datetime.datetime(2009, 4, 10, 9, 5, 59, 999999),
  datetime.datetime(2009, 4, 13, 9, 5, 59, 999999)],
 [datetime.datetime(2009, 6, 21, 9, 5, 59, 999999),
  datetime.datetime(2009, 6, 23, 9, 5, 59, 999999)],
 [datetime.datetime(2009, 8, 19, 9, 5, 59, 999999),
  datetime.datetime(2009, 8, 21, 9, 5, 59, 999999)],
 [datetime.datetime(2009, 10, 14, 9, 5, 59, 999999),
  datetime.datetime(2009, 10, 16, 9, 5, 59, 999999)],
 [datetime.datetime(2009, 12, 9, 9, 5, 59, 999999),
  datetime.datetime(2009, 12, 11, 9, 5, 59, 999999)],
 [datetime.datetime(2010, 5, 4, 9, 5, 59, 999999),
  datetime.datetime(2010, 5, 8, 9, 5, 59, 999999)],
 [datetime.datetime(2010, 12, 2, 9, 5, 59, 999999),
  datetime.datetime(2010, 12, 5, 9, 5, 59, 999999)],
 [datetime.datetime(2011, 2, 8, 9, 5, 59, 999999),
  datetime.datetime(2011, 2, 10, 9, 5, 59, 999999)],
 [datetime.datetime(2011, 5, 3, 9, 5, 59, 999999),
  datetime.datetime(2011, 5, 6, 9, 5, 59, 999999)],
 [datetime.datetime(2011, 6, 12, 9, 5, 59, 999999),
  datetime.datetime(2011, 6, 15, 9, 5, 59, 999999)],
 [datetime.datetime(2011, 8, 13, 9, 5, 59, 999999),
  datetime.datetime(2011, 8, 23, 9, 5, 59, 999999)],
 [datetime.datetime(2011, 10, 18, 9, 5, 59, 999999),
  datetime.datetime(2011, 10, 21, 9, 5, 59, 999999)],
 [datetime.datetime(2011, 11, 30, 9, 5, 59, 999999),
  datetime.datetime(2011, 12, 2, 9, 5, 59, 999999)],
 [datetime.datetime(2012, 2, 23, 9, 5, 59, 999999),
  datetime.datetime(2012, 2, 27, 9, 5, 59, 999999)],
 [datetime.datetime(2012, 4, 2, 9, 5, 59, 999999),
  datetime.datetime(2012, 4, 4, 9, 5, 59, 999999)],
 [datetime.datetime(2012, 6, 7, 9, 5, 59, 999999),
  datetime.datetime(2012, 6, 10, 9, 5, 59, 999999)],
 [datetime.datetime(2012, 7, 26, 9, 5, 59, 999999),
  datetime.datetime(2012, 8, 1, 9, 5, 59, 999999)],
 [datetime.datetime(2012, 8, 15, 9, 5, 59, 999999),
  datetime.datetime(2012, 8, 18, 9, 5, 59, 999999)],
 [datetime.datetime(2012, 10, 23, 9, 5, 59, 999999),
  datetime.datetime(2012, 10, 26, 9, 5, 59, 999999)],
 [datetime.datetime(2012, 12, 5, 9, 5, 59, 999999),
  datetime.datetime(2012, 12, 7, 9, 5, 59, 999999)],
 [datetime.datetime(2013, 2, 15, 9, 5, 59, 999999),
  datetime.datetime(2013, 2, 18, 9, 5, 59, 999999)],
 [datetime.datetime(2013, 4, 13, 9, 5, 59, 999999),
  datetime.datetime(2013, 4, 17, 9, 5, 59, 999999)],
 [datetime.datetime(2013, 6, 24, 9, 5, 59, 999999),
  datetime.datetime(2013, 6, 29, 9, 5, 59, 999999)],
 [datetime.datetime(2013, 8, 17, 9, 5, 59, 999999),
  datetime.datetime(2013, 8, 19, 9, 5, 59, 999999)],
 [datetime.datetime(2013, 10, 16, 9, 5, 59, 999999),
  datetime.datetime(2013, 10, 19, 9, 5, 59, 999999)],
 [datetime.datetime(2013, 11, 30, 9, 5, 59, 999999),
  datetime.datetime(2013, 12, 3, 9, 5, 59, 999999)],
 [datetime.datetime(2014, 1, 29, 9, 5, 59, 999999),
  datetime.datetime(2014, 1, 31, 9, 5, 59, 999999)],
 [datetime.datetime(2014, 4, 9, 9, 5, 59, 999999),
  datetime.datetime(2014, 4, 11, 9, 5, 59, 999999)],
 [datetime.datetime(2014, 5, 21, 9, 5, 59, 999999),
  datetime.datetime(2014, 5, 24, 9, 5, 59, 999999)],
 [datetime.datetime(2014, 8, 13, 9, 5, 59, 999999),
  datetime.datetime(2014, 8, 16, 9, 5, 59, 999999)],
 [datetime.datetime(2014, 10, 11, 9, 5, 59, 999999),
  datetime.datetime(2014, 10, 13, 9, 5, 59, 999999)],
 [datetime.datetime(2014, 11, 18, 9, 5, 59, 999999),
  datetime.datetime(2014, 11, 20, 9, 5, 59, 999999)],
 [datetime.datetime(2015, 3, 31, 9, 5, 59, 999999),
  datetime.datetime(2015, 4, 2, 9, 5, 59, 999999)],
 [datetime.datetime(2015, 5, 22, 9, 5, 59, 999999),
  datetime.datetime(2015, 5, 31, 9, 5, 59, 999999)],
 [datetime.datetime(2015, 8, 6, 9, 5, 59, 999999),
  datetime.datetime(2015, 8, 8, 9, 5, 59, 999999)],
 [datetime.datetime(2015, 10, 1, 9, 5, 59, 999999),
  datetime.datetime(2015, 10, 3, 9, 5, 59, 999999)],
 [datetime.datetime(2015, 11, 27, 9, 5, 59, 999999),
  datetime.datetime(2015, 11, 30, 9, 5, 59, 999999)],
 [datetime.datetime(2016, 4, 25, 9, 5, 59, 999999),
  datetime.datetime(2016, 4, 29, 9, 5, 59, 999999)],
 [datetime.datetime(2016, 6, 18, 9, 5, 59, 999999),
  datetime.datetime(2016, 6, 21, 9, 5, 59, 999999)],
 [datetime.datetime(2016, 8, 10, 9, 5, 59, 999999),
  datetime.datetime(2016, 8, 13, 9, 5, 59, 999999)],
 [datetime.datetime(2016, 10, 14, 9, 5, 59, 999999),
  datetime.datetime(2016, 10, 16, 9, 5, 59, 999999)],
 [datetime.datetime(2016, 12, 9, 9, 5, 59, 999999),
  datetime.datetime(2016, 12, 11, 9, 5, 59, 999999)],
 [datetime.datetime(2017, 2, 10, 9, 5, 59, 999999),
  datetime.datetime(2017, 2, 12, 9, 5, 59, 999999)],
 [datetime.datetime(2017, 6, 13, 9, 5, 59, 999999),
  datetime.datetime(2017, 6, 16, 9, 5, 59, 999999)],
 [datetime.datetime(2017, 8, 10, 9, 5, 59, 999999),
  datetime.datetime(2017, 8, 13, 9, 5, 59, 999999)],
 [datetime.datetime(2017, 10, 10, 9, 5, 59, 999999),
  datetime.datetime(2017, 10, 13, 9, 5, 59, 999999)],
 [datetime.datetime(2017, 12, 8, 9, 5, 59, 999999),
  datetime.datetime(2017, 12, 18, 9, 5, 59, 999999)],
 [datetime.datetime(2018, 2, 17, 9, 5, 59, 999999),
  datetime.datetime(2018, 2, 19, 9, 5, 59, 999999)],
 [datetime.datetime(2018, 4, 4, 9, 5, 59, 999999),
  datetime.datetime(2018, 4, 6, 9, 5, 59, 999999)],
 [datetime.datetime(2018, 6, 7, 9, 5, 59, 999999),
  datetime.datetime(2018, 6, 16, 9, 5, 59, 999999)],
 [datetime.datetime(2018, 8, 13, 9, 5, 59, 999999),
  datetime.datetime(2018, 8, 15, 9, 5, 59, 999999)],
 [datetime.datetime(2018, 10, 19, 9, 5, 59, 999999),
  datetime.datetime(2018, 10, 22, 9, 5, 59, 999999)],
 [datetime.datetime(2018, 12, 7, 9, 5, 59, 999999),
  datetime.datetime(2018, 12, 9, 9, 5, 59, 999999)],
 [datetime.datetime(2019, 2, 20, 9, 5, 59, 999999),
  datetime.datetime(2019, 2, 24, 9, 5, 59, 999999)],
 [datetime.datetime(2019, 4, 19, 9, 5, 59, 999999),
  datetime.datetime(2019, 4, 22, 9, 5, 59, 999999)],
 [datetime.datetime(2019, 6, 18, 9, 5, 59, 999999),
  datetime.datetime(2019, 6, 21, 9, 5, 59, 999999)],
 [datetime.datetime(2019, 8, 10, 9, 5, 59, 999999),
  datetime.datetime(2019, 8, 12, 9, 5, 59, 999999)],
 [datetime.datetime(2019, 10, 9, 9, 5, 59, 999999),
  datetime.datetime(2019, 10, 11, 9, 5, 59, 999999)],
 [datetime.datetime(2019, 12, 5, 9, 5, 59, 999999),
  datetime.datetime(2019, 12, 8, 9, 5, 59, 999999)]]

In [ ]:
def get_values_from_era5(dates, lat, lon):